### ISSUE TITLE
Problem with laravelrus/sleepingowl version 

### ISSUE THREAD

**Issue by ielyanov** [utz0r2/lashop#1]
Hello!

`$ php composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package laravelrus/sleepingowl dev-feature/5.4 exists as laravelrus/slee
1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.1.0, 1.1.1, 1.1.10, 1.1.11, 1.1.2, 1.1.3, 1.1.4, 1.1.5,
.2.3, 1.2.4, 1.2.5, 1.3.0, 1.3.1, 1.3.10, 1.3.11, 1.3.12, 1.3.13, 1.3.14, 1.3.15, 1.3.16, 1.
, 1.3.23, 1.3.24, 1.3.25, 1.3.26, 1.3.27, 1.3.28, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8,
, 2.0.14, 2.0.15, 2.0.16, 2.0.17, 2.0.18, 2.0.19, 2.0.2, 2.0.20, 2.0.21, 2.0.22, 2.0.23, 2.0
 2.0.30, 2.0.31, 2.0.32, 2.0.33, 2.0.34, 2.0.35, 2.0.36, 2.0.37, 2.0.38, 2.0.39, 2.0.4, 2.0.
0.8, 2.0.9, 3.0.0-beta, 4.0.0-beta, 4.0.1-beta, 4.0.10-beta, 4.0.16-beta, 4.0.18-beta, 4.10.
002, 4.12.45-beta, 4.12.48-beta, 4.12.55-beta, 4.12.57-beta, 4.12.60-beta, 4.13.64-beta, 4.1
, 4.15.80-beta, 4.15.83-beta, 4.15.84-beta, 4.16.86-beta, 4.17.86-beta, 4.17.87-beta, 4.17.8
.21.94-beta, 4.22.96-beta, 4.23.101-beta, 4.23.102-beta, 4.23.106-beta, 4.23.107-beta, 4.24.
, 4.32.121-beta, 4.33.128-beta, 4.33.129-beta, 4.36.133-beta, 4.37.135-beta, 4.37.136-beta,
4.40.1, 4.40.8, 4.41.8, 4.45.16, 4.48.25, 4.5.25-beta, 4.5.26-beta, 4.5.30-beta, 4.52.35, 4.
30, 4.8.35-beta, 4.82.20, 4.9.35-beta, 4.95.29, 4.99.99, dev-analysis-8wda9E, dev-analysis-X
v-dev-old, dev-development, 4.x-dev, dev-master, dev-new] but these are rejected by your con
`
How fix it?

**Comment by igoves** [comment]
@ielyanov use new version 1.1. Thanks for feedback.
