### ISSUE TITLE
How to add new controller to left menu ?

### ISSUE THREAD

**Issue by Clever91** [utz0r2/lashop#5]

**Comment by Clever91** [comment]
i am new in laravel ))

**Comment by Clever91** [comment]
i have found answer [https://packagist.org/packages/gavande/laravel-admin](url)

**Comment by Clever91** [comment]
and found some issue: `<a href="/{{ $branch['slug'] }}` branch.blade.php: 5. `slug` is not exists

**Comment by igoves** [comment]
https://github.com/utz0r2/lashop/blob/master/app/Admin/routes.php
